# Configuration file. 
# Copyright © 2018 Eduard Sesigin. All rights reserved. Contacts: <claygod@yandex.ru>


[Main]
Port = "80"

[Ethereum]
Address = "http://127.0.1.1:30303"

[Test]
From = "0x6247cf0412c6462da2a51d05139e2a3c6c630f0a"
To = "0xcfa202c4268749fbb5136f2b68f7402984ed444b"
Amount = 1
