# Microservice
# Configuration file. 
# Copyright © 2016 Eduard Sesigin. All rights reserved. Contacts: <claygod@yandex.ru>
# 
# When you change the structure of the configuration file,
# make sure the same changes need to be made to `config.go`

[Main]
Port = "80"
Name = "Microservice"

[Session]
Secure	= "something-very-secret"
Name	= "session-name"
